### ISSUE TITLE
extension config formatting error

### ISSUE THREAD

**Issue by FFroehlich** [sebapersson/petab_sciml_testsuite#1]
for hybridisation tests the sciml extension config is stored in the extensions field, rather than the "sciml" subfield:

current:
```
extensions:
  array_files:
    net1_ps_file:
      location: "net1_ps.hdf5"
      format: "HDF5"
  hybridization_file: "hybridization.tsv"
  neural_nets:
    net1:
      location: "net1.yaml"
      static: false
      format: "YAML"
```

correct:
```
extensions:
  sciml:
    array_files:
      net1_ps_file:
        location: "net1_ps.hdf5"
        format: "HDF5"
    hybridization_file: "hybridization.tsv"
    neural_nets:
      net1:
        location: "net1.yaml"
        static: false
        format: "YAML"
```
